export default {
  AUTH_FACEBOOK: 'AUTH_FACEBOOK',
  AUTH_FACEBOOK_ERROR: 'AUTH_FACEBOOK_ERROR',
  AUTH_FACEBOOK_PENDING: 'AUTH_FACEBOOK_PENDING',
  AUTH_FACEBOOK_SUCCESS: 'AUTH_FACEBOOK_SUCCESS',

  AUTH_MEDIUM: 'AUTH_MEDIUM',
  AUTH_MEDIUM_ERROR: 'AUTH_MEDIUM_ERROR',
  AUTH_MEDIUM_PENDING: 'AUTH_MEDIUM_PENDING',
  AUTH_MEDIUM_SUCCESS: 'AUTH_MEDIUM_SUCCESS',

  AUTH_REDDIT: 'AUTH_REDDIT',
  AUTH_REDDIT_ERROR: 'AUTH_REDDIT_ERROR',
  AUTH_REDDIT_PENDING: 'AUTH_REDDIT_PENDING',
  AUTH_REDDIT_SUCCESS: 'AUTH_REDDIT_SUCCESS'
};
