export default {
  FETCH_BACKGROUND_IMAGE: 'FETCH_BACKGROUND_IMAGE',
  FETCH_BACKGROUND_IMAGE_PENDING: 'FETCH_BACKGROUND_IMAGE_PENDING',
  FETCH_BACKGROUND_IMAGE_SUCCESS: 'FETCH_BACKGROUND_IMAGE_SUCCESS',
  SET_NEW_BACKGROUND_IMAGE: 'SET_NEW_BACKGROUND_IMAGE',
  SET_NEW_BACKGROUND_IMAGE_SUCCESS: 'SET_NEW_BACKGROUND_IMAGE_SUCCESS'
};
