export default {
  FETCH_WORDS: 'FETCH_WORDS',
  FETCH_WORDS_PENDING: 'FETCH_WORDS_PENDING',
  FETCH_WORDS_SUCCESS: 'FETCH_WORDS_SUCCESS',
  SET_NEW_WORD: 'SET_NEW_WORD',
  SET_NEW_WORD_PENDING: 'SET_NEW_WORD_PENDING',
  SET_NEW_WORD_SUCCESS: 'SET_NEW_WORD_SUCCESS'
};
